version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      - cd src/backend/catalog/
      - pip install -r src/release-flight/requirements.txt

  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket $PACKAGE_BUCKET --output-template-file packaged-template.yaml
      - ls

artifacts:
  discard-paths: yes
  files:
    - src/backend/catalog/packaged-template.yaml
