version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      - cd src/backend/catalog/

  build:
    commands:       
      - sam build --parallel --cached

artifacts:
  discard-paths: yes
  files:
    - src/backend/catalog/.aws-sam/build/template.yaml
  secondary-artifacts:
    release-flight:
      files:
        - src/backend/catalog/.aws-sam/build/ReleaseFlight/**
    reserve-flight:
      files:
        - src/backend/catalog/.aws-sam/build/ReserveFlight/**

cache:
  paths:
    - src/backend/catalog/.aws-sam/cache
