version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      - cd src/backend/catalog/

  build:
    commands:       
      - sam build --parallel --cached

artifacts:
  files:
    - '**/*'
  base-directory: 'src/backend/catalog/.aws-sam/build'

cache:
  paths:
    - src/backend/catalog/.aws-sam/cache/**/*
