version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      - cd src/backend/catalog/

  build:
    commands:       
      - sam build --parallel --cached

artifacts:
  discard-paths: yes
  files:
    - src/backend/catalog/.aws-sam/build/template.yaml
  secondary-artifacts:
    artifacts:
      base-directory: 'src/backend/catalog/.aws-sam/build'
      files:
        - '**/*'
      discard-paths: yes
      
    # reserve-flight:
    #   base-directory: 'src/backend/catalog/.aws-sam/build/ReserveFlight'
    #   files:
    #     - '**/*'
    #   discard-paths: yes

cache:
  paths:
    - src/backend/catalog/.aws-sam/cache
