version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      - cd src/backend/catalog/

  build:
    commands:       
      - sam build --parallel --cached

  post-build:
    commands:
      - sam package --template-file template.yaml --s3-bucket $PACKAGE_BUCKET --output-template-file packaged-template.yaml

artifacts:
  files:
    - 'src/backend/catalog/packaged-template.yaml'

cache:
  paths:
    - src/backend/catalog/.aws-sam/cache/**/*
